name: Deploy MongoDB Atlas

on:
  push:
    branches:
      - main
      - mongoDB-gcp

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          TF_VAR_mongodb_public_key: ${{ secrets.MONGODB_ATLAS_PUBLIC_KEY }}
          TF_VAR_mongodb_private_key: ${{ secrets.MONGODB_ATLAS_PRIVATE_KEY }}
          TF_VAR_org_id: ${{ secrets.ATLAS_ORG_ID }}
          TF_VAR_db_user: ${{ secrets.DB_USER }}
          TF_VAR_db_pass: ${{ secrets.DB_PASS }}

      - name: Read Terraform output (Mongo URI)
        run: |
          echo "MONGO_URI=$(terraform output -raw connection_string)" >> $GITHUB_ENV

      - name: Write MongoDB URI to other repository
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          gh secret set MONGO_URI \
            --repo group-240/tech-challenge-payments \
            --body "$MONGO_URI"
